### ISSUE TITLE
Implementar registro de auditoria

### ISSUE THREAD

**Issue by leocarreras** [melizeche/ayudapy#115]
Registro de auditoria para las acciones sobre los registros

Definir campos a auditar @melizeche

**Comment by melizeche** [comment]
el modelo HelpRequest por el momento.
probabemente podemos usar algo como https://github.com/etianen/django-reversion

@dalleng  no queres encargarte de este ticket por favor? o si tenes algo propio implementado u otras mejores prácticas metele, te cedo la decisión

**Comment by melizeche** [comment]
#183 es  lo mismo creo

**Comment by dalleng** [comment]
> el modelo HelpRequest por el momento.
> probabemente podemos usar algo como https://github.com/etianen/django-reversion
> 
> @dalleng no queres encargarte de este ticket por favor? o si tenes algo propio implementado u otras mejores prácticas metele, te cedo la decisión

Hay 2 que conozco uno es este django-reversion y otro que se llama https://django-simple-history.readthedocs.io/. Ese simple history es mas facil de usar.
