### ISSUE TITLE
Poner categorías elegibles por el solicitante para la vista de pedidos

### ISSUE THREAD

**Issue by Fespinolaprieto** [melizeche/ayudapy#14]
edited by @leocarreras : **favor ver el comentario de abajo en el issue**

Esta muy buena la plataforma. 

Se podrian poner etiquetas para agrupar a los pedidos mas comunes, por ejemplo Viveres y/o Medicamentos, Ropas para Bebes, Pañales, etc. 

Que opinas ?

**Comment by melizeche** [comment]
La idea es implementar eso esta semana

**Comment by Fespinolaprieto** [comment]
Que pena que aun no aprendí a programar. Pero genial. !!!!! Tambien se podrian agrupar las zonas o ciudades.

**Comment by katiachaparro** [comment]
Una idea sería que dichas etiquetas tengan cantidad. Así se puede ver a simple vista lo que más se necesita.
Otra idea sería colocar un sidebar en donde se listen esas etiquetas con sus cantidades[Ej: Medicamentos(34)] y poder filtrarlas mediante un buscador.

**Comment by diosnelv** [comment]
@melizeche en el branch **issue-14** cree una tabla tag, y lo relacionado como FK a help_request, agregue la vista. Estirar eso en el form de crear pedido lo que faltaría y todo el proceso de guardado

**Comment by leocarreras** [comment]
Colocar 4 categorías en botones en la vista de Agregar pedido:

-  Viveres

- Medicamentos

- Art Limpieza

- Art Bebés

**Comment by manununhez** [comment]
@leocarreras Favor verificar si este Feature/tags #144 no está relacionado al issue.

**Comment by leocarreras** [comment]
@manununhez el otro te deja crear categorias que quieras, este son los 4 botones elegibles de los que charlamos para la vista como esta el PDF, del #144 probablemente van a representar otras cosas que queramos y no va a ser elegible por el usuario

**Comment by claspina** [comment]
> @melizeche en el branch **issue-14** cree una tabla tag, y lo relacionado como FK a help_request, agregue la vista. Estirar eso en el form de crear pedido lo que faltaría y todo el proceso de guardado

@melizeche esta opción como quedo? sería válido continuar por este camino y en dicha tabla crear las 4 categorías que menciona @leocarreras para hacer la asociación?

**Comment by leocarreras** [comment]
Closed with #222
