### ISSUE TITLE
Resultados no relacionados al parámetro de busqueda - API /helprequests/

### ISSUE THREAD

**Issue by juanhuttemann** [melizeche/ayudapy#155]
Al utilizar el parámetro "title" devuelve objetos que no contienen el término de búsqueda.
![title](https://user-images.githubusercontent.com/6674725/79075645-2c7b5000-7cc2-11ea-9c5c-a8bfcf72821a.png)

**Comment by leocarreras** [comment]
Estas buscando title, y todas las serializaciones tienen eso

api/v1/helprequests/?search=pañal&search_fields=title

- search es la busqueda

- search_fields es el campo
