### ISSUE TITLE
[Ayudapy] tener una mayor accesibilidad mediante PWA

### ISSUE THREAD

**Issue by katiachaparro** [melizeche/ayudapy#16]
**Resultado esperado:** Que la App tenga mayor accesibilidad  convirtiéndola en una App, una sugerencia seria el uso  Progressive Web App(PWA). El costo de conversión es mínimo
**Prioridad:** Baja

**Comment by leocarreras** [comment]
Contributors in
IOS https://github.com/pescode/AyudaPY-iOS
Android https://gitlab.com/rubenlop88/ayudapy
close this issue
