### ISSUE TITLE
[Ayudapy][Botón de Ayuda realizada] cerrar las ayudas ya hechas para tener un mayor alcance

### ISSUE THREAD

**Issue by katiachaparro** [melizeche/ayudapy#17]
**Resultado esperado:** 
Si se realiza una ayuda creo que se tiene que cerrar para quitar de la cola de ayudas. La idea es tratar de ayudar a la mayor cantidad de personas posibles y generalmente el ojo tiende a mirar dentro de las primeras opciones.
En el caso que dicha familia necesita otra vez una ayuda es cuestión que vuelva a hacer el pedido
**Prioridad:** Media

**Comment by oscarnortiz** [comment]
Sugerencia:
cuando se crea un pedido, que en la pantalla de confirmación aparezca:
"Anotá este código: **7U6G**. Con él podrás marcar tu pedido como resuelto"

El código es un alfanumérico aleatorio de 4 digitos, lo mas simple posible.

En la pantalla principal, agregar opción "Marcar pedido como resuelto. Ingresa tu código: ____"

Al validar, la persona puede dejar un mensaje de agradecimiento al benefactor y su nombre si este está de acuerdo. También una foto si lo desea.

Todo esto es OPCIONAL. La idea no es complicar el uso, sino ofrecer esa opción y la gente se irá acostumbrando a usarlo. Si le es complicado, no lo usa y listo. Su pedido irá bajando con el tiempo. 
Creo que es importante marcar pedidos como resueltos, ya que ayuda a organizar los pedidos y el feedback genera sensacion positiva de que la plataforma funciona.

**Comment by leocarreras** [comment]
Tambien la opcion de Marcelo es valida, dejar que la gente pueda comentar como si fuera un hilo, entonces seguimos sin necesitar registros

**Comment by gomezag** [comment]
> Tambien la opcion de Marcelo es valida, dejar que la gente pueda comentar como si fuera un hilo, entonces seguimos sin necesitar registros

Aunque eso no quita el problema de que se llene el mapa de pedidos viejos... 
Habría que combinar con algún filtro que haga flotar visualmente a los pedidos recientes y/o con más actividad

**Comment by gomezag** [comment]
Aunque, creo que la opción de @oscarnortiz puede ser muy viable para que los usuarios puedan darle resolve.
Y si combinamos con los comentarios, se puede agregar un campo no obligatorio de email para enviar notificaciones cuando alguien publique un comentario en el pedido.

**Comment by joaquinolivera** [comment]
Si la ayuda fue recibida debe ser acción del que solicito la ayuda de cerrar el pedido... Si no dejas abierta la posibilidad de que gente cierre pedido de ayuda sin haberla recibido y es más peligroso que quede el pedido abierto

**Comment by X1lef** [comment]
**Sugerencia:**

Otra opción también podría ser que en el query se le configure para que se traiga solo los pedidos que están en el rango de una semana por ejemplo. Se le podría indicar con un mensaje al usuario que los pedidos tiene un tiempo de visibilidad de una semana.

En lo personal creo que lo del cerrar el pedido no funcionara, considero que no todas las personas que solicitan una ayuda lo van a cerrar.

**Comment by jrgonzalez3** [comment]
Cómo podemos priorizar este pedido..? También se puede cambiar de color el pedido en vez de cerrar .. como.. ayudado 1 vez o gracias

**Comment by alefq** [comment]
Está clara la necesidad de filtrar los pedidos. 
Como comentaron, una opción es con intervención, del que ayuda o del que recibió la ayuda. 

Yo propongo otra, anexo a la opción que ya se viene debatiendo. 
Ponerle un TTL al pedido, y que haya una zona de starvation, si no tuvo actividad en un cierto tiempo. 
Esto podría ser colocando un filtro default al mapa de "x días", y si alguien quiere revivir su pedido, que entre a comentar o editar. 
Si la persona que la realizó lo "reaviva", entonces puede volver a aparecer en el mapa; o si tuvo alguna actividad.

**Comment by leocarreras** [comment]
#274 partially closes this issue, as only one request per phone number is allowed, and a new request deactivates the previous one
