### ISSUE TITLE
Like o dislike permite realizar varias veces

### ISSUE THREAD

**Issue by BlasFerna** [melizeche/ayudapy#176]
Cada vez que hago click en like o dislike incrementa el valor.

![image](https://user-images.githubusercontent.com/8385910/79127965-c1d51d80-7d70-11ea-8e01-ad2b0043082b.png)

Según mi criterio debería permitir una sola vez.

**Comment by melizeche** [comment]
De acuerdo, con los últimos cambios realizados en cuanto a sesiones ya podríamos limitarlo. 
Gracias por reportar!
