### ISSUE TITLE
Remove properties from JSON returned by helprequestsgeo

### ISSUE THREAD

**Issue by jorgeramirez** [melizeche/ayudapy#186]
Currently `/api/v1/helprequestsgeo` returns roughly the complete HelpRequest model. This service we use in the list_request page (and also in the mobile versions of the website). I believe we should make the returned JSON as minimal as possible, which would affect (positively) the performance on this page.

One idea (we should debate on this), is to make it return just the ID and Lat/Long properties. This assumes that we introduce a new service that can take a list of IDs (with at most X number of entries) and returns the list of help_request objects matching the input IDs.

Thoughts?

**Comment by melizeche** [comment]
@jorgeramirez Already talked with Victor about the mobile app, he's going to get the details from `/api/v1/helprequests` so we can safely remove most fields from the serializer, I'll suggest return only `pk`, `title`, `name` and `added` (added I think is used on the list), that would not brake any change and it's a quick thing to do to gain performance

If you're ok this just make the change and let's test it in dev

**Comment by jorgeramirez** [comment]
sure @melizeche, I'll do it later tonight.
