### ISSUE TITLE
Privacidad - teléfonos

### ISSUE THREAD

**Issue by leocarreras** [melizeche/ayudapy#21]
Agregar CAPTCHA o mostrar como imagen para evitar robo fácil de datos

**Comment by ivanfretes** [comment]
Propongo
- Agregar un Botón llamar y un botón enviar whatsapp, ocultando los números de teléfono.

**Comment by ivanfretes** [comment]
> Agregar CAPTCHA o mostrar como imagen para evitar robo fácil de datos

**Comment by ivanfretes** [comment]
Agregar un Botón llamar y un botón enviar whatsapp, ocultando los números de teléfono.

**Comment by jorgeramirez** [comment]
I'll give this issue a try.
