### ISSUE TITLE
Mensaje de error al omitir el campo Ubicación

### ISSUE THREAD

**Issue by juanhuttemann** [melizeche/ayudapy#213]
Debe tener un mensaje más claro para el usuario

![ubicacion](https://user-images.githubusercontent.com/6674725/79408621-c3b60100-7f69-11ea-8a0e-c20b749c66d6.png)

**Comment by melizeche** [comment]
100% de acuerdo

**Comment by melizeche** [comment]
Fixed in commit e15e316e1ebb01dccc5f85182c24a4f7f11ad9ed

![Screenshot_2020-04-16  AyudaPy (2)](https://user-images.githubusercontent.com/484773/79440566-288e4d00-7fa4-11ea-96d0-bf98df1dfc90.png)
