### ISSUE TITLE
bad pagination messages in donation centers view

### ISSUE THREAD

**Issue by melizeche** [melizeche/ayudapy#215]
@manununhez can you take a look at this pls?
![Screenshot_2020-04-16  AyudaPy ](https://user-images.githubusercontent.com/484773/79427244-54083c00-7f92-11ea-8490-92036d9a9651.png)

**Comment by manununhez** [comment]
@melizeche No puedo reproducir el error. Te continua saliendo?
Lo que pude notar es que, en Chrome por lo menos, para actualizar el .js que utiliza la paginación,
se necesita hacer un hard reload a la página.
Si te aparece de vuelta, fijate si esta cargando la versión actualizada del list.js y list-donation.js

**Comment by melizeche** [comment]
:facepalm: tenés toda la razón, con hard reload ya se soluciona, sorry
