### ISSUE TITLE
Create Dashboard with HelpRequests per day/week, most visited, etc..

### ISSUE THREAD

**Issue by melizeche** [melizeche/ayudapy#240]

**Comment by jorgeramirez** [comment]
Library options (just a quick google)

* https://c3js.org/ 
* https://www.chartjs.org/
* https://apexcharts.com/ (this one seems to be the most popular).

**Comment by jorgeramirez** [comment]
Some  interesting charts to consider

* X = requests Y = time, where time in {day, week, month}
* X = requests Y = visited times.
* Pie chart with %created  and %resolved. This will show from the total number of requests how many have been assisted.
    * We have the “resolved” column in the HelpRequest model.
* Choropleth map of help requests. On hover, show the top-k cities with requests (could be k = 5).
    * e.g., https://github.com/voluntadpear/vue-choropleth

**Comment by melizeche** [comment]
I'll say first let's  create the API endpoint to get this data
Total active HR = `HelpRequest.objects.filter(active=True, resolved=False).count()`
Total active HR unique phone numbers = `HelpRequest.objects.filter(active=True, resolved=False).distinct('phone').count()`
Mark as resolved = `HelpRequest.objects.filter(resolved=True).count()`
Today = `HelpRequest.objects.filter(active=True, added__gte=date.today()).count()`
yesterday = `HelpRequest.objects.filter(active=True, added__lt=date.today(), added__gte=date.today()-timedelta(days=1)).count()`

**Comment by jorgeramirez** [comment]
Yes, I guess we could do:

We can implement the services
* `/stats/requests-count?by=day|week|month`
    * This service return a count summary per day/week/month which will make it very compact. Maybe this service could return assisted and pending as two properties and within these we have the frequency over day/week/month.
* `/stats/summary`
    * This will return HR total active, HR total active unique phone number, and Total HR marked as resolved.

The above covers what you mentioned.

**Comment by jorgeramirez** [comment]
Oh, you already add the summary service, great!

**Comment by jorgeramirez** [comment]
I guess we can close this issue unless there are other stats that could be added.
