### ISSUE TITLE
Deshabilitar un pedido anterior si Coincide datos del solicitante con numero de contacto

### ISSUE THREAD

**Issue by jcroot** [melizeche/ayudapy#256]
Para evitar que se dupliquen los pedidos, aquel usuario que publique con los mismos datos de numero de contacto y nombre, que deshabilite automaticamente el anterior, para evitar duplicacion.

Entonces queda el nuevo pedido como activo. Y agregar un contador de cantidad que usuario (numero de contacto) pide en la plataforma.

**Comment by melizeche** [comment]
Muy buen approach y transparente para el usuario, yo diría que el teléfono nomas sea el identificador
