### ISSUE TITLE
Abrir el mapa en la ciudad seleccionada en pagina de filtro por ciudad

### ISSUE THREAD

**Issue by gomezag** [melizeche/ayudapy#27]
El mapa se carga en la ubicacion por defecto. Deberia cargarse centrado en la ciudad que se está mirando.

**Comment by melizeche** [comment]
+1
hay que jugar con JS probablemente, se debería agarrar el location de cualquiera de los puntos al menos para centrar el mapa, la otra sería hacer un query para obtener lat/lon de la ciudad
