### ISSUE TITLE
Salto del Guairá duplicado en selector de Ciudades

### ISSUE THREAD

**Issue by juanhuttemann** [melizeche/ayudapy#289]
![salto1](https://user-images.githubusercontent.com/6674725/80462760-311c4700-8905-11ea-89f5-5ed86f1ef36d.png)

En el datalist:
![salto2](https://user-images.githubusercontent.com/6674725/80462770-34afce00-8905-11ea-97c1-9dd128d8b070.png)

**Comment by melizeche** [comment]
hay que darle un `distinct('city_code')` probablemente
