### ISSUE TITLE
Add preview for twitter and fb links

### ISSUE THREAD

**Issue by melizeche** [melizeche/ayudapy#3]
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
https://developers.facebook.com/docs/sharing/webmasters/

**Comment by cabupy** [comment]
El último es el que esta bien: a4665e4

**Comment by leocarreras** [comment]
#37 Puede ser que resuelva

**Comment by cabupy** [comment]
@leocarreras totalmente, mucho mejor. #37
