### ISSUE TITLE
Añadir Autenticación Opcional poder enviar publicaciones Privadas a Grupos

### ISSUE THREAD

**Issue by crmun** [melizeche/ayudapy#39]
Por defecto que las publicaciones sean públicas y sin registrarse tal como está hoy.

Que adicionalmente se pueda autenticar en forma opcional por Facebook (requerido para publicaciones privadas) con el fin de permitir la publicación a Grupos (propios del sistema o Grupos de Facebook). Cuando la publicación es de grupo se puede exigir autenticación para el caso y validar pertenencia a Grupo..

Para facilitar la implementación de compartir a Grupos se puede usar el mecanismo URL Oculta (que utilizan Youtube o Forms de Office y Google entre otros). Luego todo el que tenga la URL podrá acceder.

**Comment by crmun** [comment]
El objetivo es buscar integrar grupos existentes con miles de usuarios en Facebook incorporándolos a la plataforma

**Comment by leocarreras** [comment]
Los botones sociales en la parte de abajo de cada pedido te brindan esa opcion, creeria. Te permite compartir a cualquier grupo que tu usuario tenga habilitado.

**Comment by crmun** [comment]
Tal cual pero aquí estamos hablando de compartir SOLO con un grupo, es decir, en forma Privada, visible solo para el grupo y no para todo el mundo...

El objetivo de esto es que un grupo de personas puede ser alentado a la acción por sus líderes.. Por ejemplo, grupos de católicos, de evangélicos, masones, mormones o Testigos de Jehová... Las personas pueden sentirse más motivadas a ayudar dentro de su grupo de prioridad. Todos tienen prioridades (primero su familia, luego su comunidad, su barrio, etc.) y como la capacidad de cada uno es limitada, básicamente así tendrías varios líderes sintiendo la aplicación y la causa como propia y utilizándola como herramienta core dentro de su comunidad... Pero tienes que permitirle a la gente tener sus espacios y libertades para organizarse y agruparse como mejor les parezca.

**Comment by crmun** [comment]
Inclusive podrías darle privilegios de moderador a alguien dentro de un grupo para encargarse de que no se salga de control con Spam

**Comment by crmun** [comment]
Cadad grupo puede luego tener su propia URL:

https://ayudapy.org/convencion_evangelica
https://ayudapy.org/iglesia_catolica
https://ayudapy.org/asuncion_en_bici
https://ayudapy.org/exa_ctn
