### ISSUE TITLE
Agrupar pedidos por numero de telefono

### ISSUE THREAD

**Issue by ivanfretes** [melizeche/ayudapy#51]
- Si la persona solicito más de una ayuda, visualizar las solicitudes relacionadas

**Comment by migueljoba** [comment]
Gracias @ivanfretes , me parece muy útil saber cuántos pedidos existen para la misma persona. Ahora, el único identificador que tenemos es el nro de teléfono.

¿Más o menos cómo podría ser la interfaz?
