### ISSUE TITLE
get city by geolocation and make a filter for that

### ISSUE THREAD

**Issue by melizeche** [melizeche/ayudapy#8]

**Comment by gomezag** [comment]
https://github.com/gomezag/ayudapy/commits/dev2

una solución inicial. 
primero pensé hacer un @property, pero no se pueden filtrar. 
La solución está en hacer un field city en el modelo que guarde la ciudad en formato bonito, y city_code que guarde la ciudad normalizada (sin acentos, sin espacios). 

Todas las entradas del modelo HelpRequest tiene que actualizarse haciendo 

for obj in HelpRequest.objects.all():
   obj.save()

para que se actualize la info de ciudad en cada instancia.

no sé si vale la pena hacer un pull request en este punto.

**Comment by melizeche** [comment]
Mil Gracias!
