### ISSUE TITLE
Guardar foto de vivienda

### ISSUE THREAD

**Issue by X1lef** [melizeche/ayudapy#85]
Agregar en el formulario de pedidos la opción de obtener la foto de la vivienda (dato opcional), esto permitirá a las personas tener mas referencias para hallar la ubicación de la persona que necesita ayuda. Esta imagen se mostrara en el popup del mapa.

**Comment by melizeche** [comment]
Creo que es agregar algo mas al formulario y eso afectaria a la simplicidad de la plataforma, actualmente ya se puede cargar una foto que se podria usar para eso
